name: Layotto Java SDK Dev Pipeline ğŸŒŠ

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    #	é…ç½®æƒé™
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # ä¸‹è½½ä»£ç 
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        # å®‰è£… JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      # Maven æ‰“åŒ…
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # å°†æ‰“åŒ…å¥½çš„ Jar åŒ… æ”¾åˆ° staging æ–‡ä»¶å¤¹
      - name: cp Jar
      - run: cp examples-preview-service/target/*.jar docker/preview_server && ls docker/preview_server

      - name: Build preview_server Image
        run: docker build -t layotto/preview_server:latest -f docker/preview_server/Dockerfile .

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: "2429727684@qq.com"
#          password: "lixingpeng123+++"

      - name: Push Image
        run: |
          docker push layotto/preview_server:latest


