#name: Layotto Java SDK Dev Pipeline üåä
#
#on:
#  push:
#    branches: [main]
#    paths-ignore:
#      - 'docs/**'
#      - '**/*.md'
#  pull_request:
#    branches: "*"
#    paths-ignore:
#      - 'docs/**'
#      - '**/*.md'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'temurin'
#
#
#
name: Java CI with Maven

# Ê£ÄÊµãÂà∞ src Êñá‰ª∂ÂÜÖ .java Êñá‰ª∂ÊúâÂèòÂä®ÊâßË°åÁºñËØë
on:
  push:
    paths:
      - '**/*src/**/*.java'

jobs:
  build:
    #	ÈÖçÁΩÆÊùÉÈôê
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # ‰∏ãËΩΩ‰ª£Á†Å
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        # ÂÆâË£Ö JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Maven ÊâìÂåÖ
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # Â∞ÜÊâìÂåÖÂ•ΩÁöÑ Jar ÂåÖ ÊîæÂà∞ staging Êñá‰ª∂Â§π
      - run: mkdir staging && cp target/*.jar staging
#      # ËÆæÁΩÆ jobs Maven pom ÁâàÊú¨ÁéØÂ¢ÉÂèòÈáè
#      - name: Set Release version env variable
#        run: |
#          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
#      - name: "Build & test"
#        run: |
#          echo "done!"
#      # ‰∏ä‰º†Êñá‰ª∂Âπ∂ÂèëÂ∏É Release
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
#          prerelease: false
#          title: "Release ${{ env.RELEASE_VERSION }}"
#          files: |
#            staging/*.jar

